### ISSUE TITLE
STA failing

### ISSUE THREAD

**Issue by dsnaveen1** [kunalg123/vsdflow#3]
after running post STA failing without any log file creation

**Comment by kunalg123** [comment]
Really apologize for such a huge delay in responding. Mostly, other are reporting issues over my udemy channel, so didn't had a chance to check this 

I have to fix this, till then here's the workaround:
From vsdflow directory, do the below:
unzip OpenSTA-master.zip
cd OpenSTA-master
mkdir build
cd build
cmake ..
make
cd ..
sudo rm -rf /usr/bin/sta
sudo ln -s $PWD/app/sta /usr/bin/sta

Now try running vsdflow again and see if it works

**Comment by dsnaveen1** [comment]
Thanks Kunal,

It is working now

**Comment by dsnaveen1** [comment]
now lvs is failing ,


/usr/local/share/qflow/bin/netgen: 34: /usr/local/share/qflow/bin/netgen: Bad substitution
netgen failure:  No file comp.out.
Premature exit.
Synthesis flow stopped due to error condition.
